import { NextFunction, Request, Response } from "express";
import { ZodSchema } from "zod";
import { AppError, ValidationError } from "./error-handler";
import { sendValidationError } from "../utils/error";

/*
This function returns a middleware.

(schema: ZodSchema) =>
    means the function first receives a Zod schema.

(req, res, next) =>
    is the actual Express middleware that will run for the request.

This pattern is called a "middleware factory".
It lets us reuse the same middleware logic with different schemas.
*/
export const validate =
	(schema: ZodSchema) => (req: Request, res: Response, next: NextFunction) => {
		// safeParse validates the input WITHOUT throwing an exception.
		// Instead it returns an object like:
		// { success: true, data: ... }
		// or
		// { success: false, error: ... }
		const result = schema.safeParse(req.body);

		// result.success tells us whether validation passed
		if (!result.success) {
			const formattedErrors: Record<string, string> = {};

			// result.error.issues
			// When validation fails, Zod provides an array called `issues`.
			// Each "issue" describes one validation error (field, rule broken, message, etc.).

			result.error.issues.forEach((issue) => {
				/*
        forEach(...)
        This loops through every validation error in the issues array.

        Example issues array:
        [
           {
                path: ["password"],
                message: "Too small: expected string to have >=8 characters"
            }
        ]
        */

				// issue.path
				// `path` is an array representing where the error occurred in the object.
				// Example: ["password"] means the error is in req.body.password
				// For nested objects it could be something like ["user", "email"]

				const field = issue.path[0] as string;

				/*
        issue.path[0]
        We take the first element of the path array because it represents
        the top-level field name.

        Example:
        path = ["password"] → field = "password"

        `as string`
        This is a TypeScript type assertion.
        It tells TypeScript: "Trust me, this value is a string."
        */

				// formattedErrors[field]
				// This dynamically creates a key in the formattedErrors object.

				// Example result:
				// formattedErrors = {
				//   password: "Too small: expected string to have >=8 characters"
				// }

				formattedErrors[field] = issue.message;

				/*
        issue.message
        This is the human-readable error message generated by Zod.

        Example:
        "Too small: expected string to have >=8 characters"
        */
			});

			// Convert Record<string, string> → ErrorField[]
			const errorArray = Object.entries(formattedErrors).map(
				([field, message]) => ({
					field,
					message,
				}),
			);

			// If validation fails, we return a 400 response
			// and stop the request from reaching the controller
			return sendValidationError(res, errorArray);
		}

		/*
    If validation succeeds, result.data contains the validated
    and correctly typed data.

    We overwrite req.body with the validated data so that:
    - unknown fields are removed
    - types are guaranteed to match the schema
    */
		req.body = result.data;

		// next() passes control to the next middleware/controller
		next();
	};
